/*
 * Marvin - an UCI/XBoard compatible chess engine
 * Copyright (C) 2015 Martin Danielsson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * Note: This file is autogenerated. Do not edit.
 */

#include "evalparams.h"

int DOUBLE_PAWNS_MG = -19;
int DOUBLE_PAWNS_EG = -22;
int ISOLATED_PAWN_MG = -14;
int ISOLATED_PAWN_EG = -14;
int ROOK_OPEN_FILE_MG = 41;
int ROOK_OPEN_FILE_EG = 5;
int ROOK_HALF_OPEN_FILE_MG = 18;
int ROOK_HALF_OPEN_FILE_EG = 18;
int QUEEN_OPEN_FILE_MG = 0;
int QUEEN_OPEN_FILE_EG = 12;
int QUEEN_HALF_OPEN_FILE_MG = 13;
int QUEEN_HALF_OPEN_FILE_EG = 8;
int ROOK_ON_7TH_MG = 0;
int ROOK_ON_7TH_EG = 22;
int BISHOP_PAIR_MG = 30;
int BISHOP_PAIR_EG = 68;
int PAWN_SHIELD_RANK1 = 32;
int PAWN_SHIELD_RANK2 = 28;
int PAWN_SHIELD_HOLE = -6;
int PASSED_PAWN_RANK2_MG = 0;
int PASSED_PAWN_RANK3_MG = 0;
int PASSED_PAWN_RANK4_MG = 0;
int PASSED_PAWN_RANK5_MG = 26;
int PASSED_PAWN_RANK6_MG = 64;
int PASSED_PAWN_RANK7_MG = 172;
int PASSED_PAWN_RANK2_EG = 15;
int PASSED_PAWN_RANK3_EG = 14;
int PASSED_PAWN_RANK4_EG = 39;
int PASSED_PAWN_RANK5_EG = 72;
int PASSED_PAWN_RANK6_EG = 118;
int PASSED_PAWN_RANK7_EG = 186;
int KNIGHT_MOBILITY_MG = 6;
int BISHOP_MOBILITY_MG = 7;
int ROOK_MOBILITY_MG = 4;
int QUEEN_MOBILITY_MG = 4;
int KNIGHT_MOBILITY_EG = 1;
int BISHOP_MOBILITY_EG = 5;
int ROOK_MOBILITY_EG = 4;
int QUEEN_MOBILITY_EG = 6;
int PSQ_TABLE_PAWN_MG[NSQUARES] = {
    0, 0, 0, 0, 0, 0, 0, 0,
    -23, -23, -21, -21, -15, 10, 13, -35,
    -16, -21, -16, -7, 2, -1, 16, -8,
    -11, -14, -5, 11, 7, 16, 1, -17,
    -14, -1, 11, 20, 25, 42, -1, 5,
    28, 23, 48, 14, 72, 127, 59, 54,
    58, 63, 55, 40, 11, -90, -131, -85,
    0, 0, 0, 0, 0, 0, 0, 0
};
int PSQ_TABLE_KNIGHT_MG[NSQUARES] = {
    -131, -40, -44, -17, -17, -6, -55, 16,
    -50, -25, -27, 7, 8, 0, -18, 2,
    -30, -19, -4, 19, 27, 6, 16, -14,
    -8, 1, 13, 16, 32, 24, 54, 7,
    20, 5, 32, 58, 24, 54, 19, 49,
    -34, 22, 60, 53, 144, 144, 21, 38,
    -56, -27, 4, 38, 8, 111, 6, -35,
    -136, -145, 18, -7, 30, -97, -75, -74
};
int PSQ_TABLE_BISHOP_MG[NSQUARES] = {
    -17, -2, -6, -20, -11, -9, 48, -22,
    19, 7, 17, -3, 18, 13, 30, -28,
    -7, 14, 13, 5, 8, 27, 1, 18,
    -20, -5, 13, 29, 23, -21, 8, 5,
    -13, 3, 24, 48, 19, 22, -12, 10,
    1, 1, -15, 20, -41, 101, 41, 4,
    -26, -9, -53, -11, -28, -46, -45, -46,
    -72, -43, -31, -7, -4, -1, -25, -68
};
int PSQ_TABLE_ROOK_MG[NSQUARES] = {
    -15, 3, 11, 12, 15, 19, 28, -1,
    -35, -16, -7, 7, -3, 14, 43, -14,
    -46, -30, -14, -14, -8, -8, 43, 20,
    -35, -38, -22, -18, -19, -22, 33, -1,
    -8, 3, 2, 12, 17, 7, 27, 19,
    -6, 21, 32, 29, 90, 88, 91, 17,
    -7, -12, 46, 23, 46, 57, 48, 134,
    47, 56, 46, 56, 29, 48, 61, 69
};
int PSQ_TABLE_QUEEN_MG[NSQUARES] = {
    19, 11, 31, 17, 43, -15, 14, -14,
    25, 4, 11, 19, 19, 60, 12, 6,
    -10, 1, 6, -2, 9, 22, 22, 14,
    -9, -36, -11, 8, 2, 14, 6, 24,
    -8, -25, -13, 1, 22, -11, 14, 36,
    -11, 19, -19, -4, 6, 126, 104, 66,
    6, -70, -29, -56, 2, 48, -35, 63,
    -19, -5, 40, 34, 19, 99, 113, 97
};
int PSQ_TABLE_KING_MG[NSQUARES] = {
    -19, -16, -57, -81, 25, -66, 3, -5,
    8, -27, -18, -46, -19, -32, 27, 27,
    -9, -1, -11, -44, -38, -36, -42, -71,
    -12, 13, -65, -78, -84, -64, -43, -72,
    -62, -59, -129, -139, -167, -71, 21, -108,
    66, 23, -4, -92, -75, -3, 29, 74,
    140, 63, 30, 62, 59, 67, 49, 159,
    -36, 192, 200, 144, 99, 200, 200, 38
};
int PSQ_TABLE_PAWN_EG[NSQUARES] = {
    0, 0, 0, 0, 0, 0, 0, 0,
    27, 27, 11, -12, 24, 16, 9, 14,
    25, 29, 12, 18, 14, 22, 6, 10,
    36, 40, 22, 6, 15, 21, 25, 21,
    61, 48, 24, 7, 15, 16, 34, 34,
    82, 73, 49, 8, -13, 14, 30, 51,
    45, 23, 22, -42, -15, 29, 48, 40,
    0, 0, 0, 0, 0, 0, 0, 0
};
int PSQ_TABLE_KNIGHT_EG[NSQUARES] = {
    -20, -40, -18, -1, 4, -25, -37, -109,
    -50, 6, 2, 0, -8, -5, 15, -35,
    -38, 17, 18, 30, 22, -1, -13, -42,
    -5, 31, 45, 27, 38, 29, 11, -11,
    21, 34, 40, 38, 40, 38, 31, 4,
    14, 32, 35, 35, -9, 4, 24, 2,
    -2, 19, 24, 39, 33, 0, 0, -11,
    -32, 42, 23, 26, 13, 45, 43, -69
};
int PSQ_TABLE_BISHOP_EG[NSQUARES] = {
    1, -12, -3, 11, -4, 14, -23, -25,
    2, -7, -3, 8, 0, 8, -3, -8,
    11, 11, 10, 10, 24, -4, 14, 24,
    23, 6, 12, 12, 5, 26, -1, 9,
    19, 8, 8, 11, 13, 8, 19, -3,
    3, 28, 22, 4, 42, -1, 19, 24,
    12, 0, 40, 46, 22, 33, 23, 8,
    18, 32, 23, 28, 13, 17, 12, 17
};
int PSQ_TABLE_ROOK_EG[NSQUARES] = {
    25, 16, 19, 16, -1, 15, 2, 1,
    15, 26, 21, 8, 11, -3, -22, -1,
    31, 27, 24, 12, 2, 11, -23, -22,
    41, 52, 41, 35, 29, 43, 12, 15,
    44, 49, 50, 44, 35, 46, 28, 26,
    51, 48, 51, 37, 15, 26, 21, 30,
    39, 46, 29, 45, 25, 24, 26, 4,
    30, 36, 39, 35, 48, 47, 47, 31
};
int PSQ_TABLE_QUEEN_EG[NSQUARES] = {
    -68, -72, -82, -21, -66, -38, -53, -12,
    -34, -31, -10, -31, -10, -102, -75, -44,
    -7, -4, 0, -13, 4, 13, 7, -30,
    37, 43, 4, 15, 24, 44, 38, 57,
    1, 53, 38, 40, 37, 103, 103, 89,
    6, 16, 62, 78, 107, 44, 74, 76,
    7, 71, 77, 125, 112, 58, 89, 57,
    12, 16, 35, 36, 57, 76, 3, 4
};
int PSQ_TABLE_KING_EG[NSQUARES] = {
    -95, -62, -29, -23, -55, -29, -69, -81,
    -18, -11, -3, 10, 3, -1, -19, -33,
    -47, 5, 5, 19, 25, 13, 8, -3,
    -12, 12, 31, 40, 40, 41, 26, 2,
    26, 60, 65, 60, 70, 64, 56, 56,
    29, 59, 68, 68, 67, 77, 93, 41,
    -34, 72, 76, 59, 69, 97, 118, 33,
    -100, -35, 0, 30, 36, 27, 24, -81
};
int KNIGHT_MATERIAL_VALUE_MG = 344;
int BISHOP_MATERIAL_VALUE_MG = 348;
int ROOK_MATERIAL_VALUE_MG = 488;
int QUEEN_MATERIAL_VALUE_MG = 1184;
int KNIGHT_MATERIAL_VALUE_EG = 339;
int BISHOP_MATERIAL_VALUE_EG = 339;
int ROOK_MATERIAL_VALUE_EG = 600;
int QUEEN_MATERIAL_VALUE_EG = 1120;
int KING_ATTACK_SCALE_MG = 27;
int KING_ATTACK_SCALE_EG = 1;
int TWO_KING_ATTACKERS_WEIGHT = 45;
int THREE_KING_ATTACKERS_WEIGHT = 100;
int FOUR_KING_ATTACKERS_WEIGHT = 100;
int FIVE_KING_ATTACKERS_WEIGHT = 100;
int SIX_KING_ATTACKERS_WEIGHT = 100;
int MANY_KING_ATTACKERS_WEIGHT = 100;
