/*
 * Marvin - an UCI/XBoard compatible chess engine
 * Copyright (C) 2015 Martin Danielsson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * Note: This file is autogenerated. Do not edit.
 */

#include "evalparams.h"

int DOUBLE_PAWNS_MG = -23;
int DOUBLE_PAWNS_EG = -23;
int ISOLATED_PAWN_MG = -14;
int ISOLATED_PAWN_EG = -14;
int ROOK_OPEN_FILE_MG = 37;
int ROOK_OPEN_FILE_EG = 13;
int ROOK_HALF_OPEN_FILE_MG = 21;
int ROOK_HALF_OPEN_FILE_EG = 21;
int QUEEN_OPEN_FILE_MG = 3;
int QUEEN_OPEN_FILE_EG = 3;
int QUEEN_HALF_OPEN_FILE_MG = 14;
int QUEEN_HALF_OPEN_FILE_EG = 14;
int ROOK_ON_7TH_MG = 13;
int ROOK_ON_7TH_EG = 16;
int BISHOP_PAIR_MG = 39;
int BISHOP_PAIR_EG = 58;
int PAWN_SHIELD_RANK1 = 32;
int PAWN_SHIELD_RANK2 = 30;
int PAWN_SHIELD_HOLE = -5;
int PASSED_PAWN_RANK2_MG = 1;
int PASSED_PAWN_RANK3_MG = 0;
int PASSED_PAWN_RANK4_MG = 0;
int PASSED_PAWN_RANK5_MG = 32;
int PASSED_PAWN_RANK6_MG = 69;
int PASSED_PAWN_RANK7_MG = 179;
int PASSED_PAWN_RANK2_EG = 12;
int PASSED_PAWN_RANK3_EG = 12;
int PASSED_PAWN_RANK4_EG = 37;
int PASSED_PAWN_RANK5_EG = 69;
int PASSED_PAWN_RANK6_EG = 116;
int PASSED_PAWN_RANK7_EG = 182;
int KNIGHT_MOBILITY_MG = 6;
int BISHOP_MOBILITY_MG = 7;
int ROOK_MOBILITY_MG = 5;
int QUEEN_MOBILITY_MG = 3;
int KNIGHT_MOBILITY_EG = 0;
int BISHOP_MOBILITY_EG = 5;
int ROOK_MOBILITY_EG = 3;
int QUEEN_MOBILITY_EG = 8;
int PSQ_TABLE_PAWN_MG[NSQUARES] = {
    0, 0, 0, 0, 0, 0, 0, 0,
    -18, -18, -21, -19, -16, 10, 12, -31,
    -9, -12, -13, -4, 6, 1, 18, -7,
    -6, -9, -2, 11, 10, 18, 4, -12,
    -13, 3, 11, 21, 25, 41, -6, 7,
    31, 21, 43, 6, 68, 126, 54, 52,
    57, 64, 49, 42, 14, -83, -116, -61,
    0, 0, 0, 0, 0, 0, 0, 0
};
int PSQ_TABLE_KNIGHT_MG[NSQUARES] = {
    -128, -38, -43, -17, -15, -7, -54, 18,
    -47, -26, -26, 9, 9, -1, -20, 1,
    -27, -15, -2, 21, 32, 9, 19, -12,
    -6, 7, 17, 22, 37, 31, 62, 12,
    23, 10, 36, 65, 40, 68, 32, 66,
    -33, 23, 64, 69, 165, 148, 31, 54,
    -56, -28, 10, 56, 18, 124, 18, -15,
    -120, -144, 26, 12, 35, -84, -53, -68
};
int PSQ_TABLE_BISHOP_MG[NSQUARES] = {
    -16, -5, -7, -23, -17, -13, 43, -24,
    18, 6, 16, -7, 14, 7, 24, -27,
    -4, 16, 14, 3, 6, 22, 0, 16,
    -21, -4, 13, 34, 25, -20, 10, 6,
    -16, 1, 31, 49, 27, 29, -10, 21,
    -4, 0, -14, 26, -24, 108, 50, 17,
    -26, -19, -49, -10, -12, -40, -33, -34,
    -76, -43, -18, 2, 5, 14, -27, -57
};
int PSQ_TABLE_ROOK_MG[NSQUARES] = {
    -13, 3, 13, 12, 12, 16, 25, -1,
    -35, -12, -6, 1, -4, 12, 45, -14,
    -43, -25, -12, -13, -8, -1, 46, 22,
    -34, -33, -24, -15, -21, -22, 42, 9,
    -8, 1, 8, 12, 21, 18, 32, 26,
    -1, 24, 34, 41, 94, 96, 100, 25,
    -3, -11, 48, 33, 53, 57, 53, 134,
    50, 54, 45, 51, 52, 48, 61, 65
};
int PSQ_TABLE_QUEEN_MG[NSQUARES] = {
    15, 6, 23, 13, 33, -26, -4, -19,
    13, -1, 6, 11, 11, 50, 3, 2,
    -14, -2, 1, -6, 6, 19, 21, 15,
    -10, -33, -13, 8, 4, 19, 12, 30,
    -10, -29, -10, 10, 27, -3, 18, 45,
    -12, 14, -13, 10, 17, 129, 100, 71,
    5, -69, -21, -37, 17, 58, -31, 67,
    -10, 0, 40, 35, 24, 96, 106, 111
};
int PSQ_TABLE_KING_MG[NSQUARES] = {
    -17, -12, -53, -82, 27, -66, 8, 5,
    9, -32, -32, -59, -30, -40, 18, 33,
    -12, -9, -26, -69, -54, -51, -44, -67,
    -12, 10, -61, -78, -90, -63, -40, -66,
    -60, -58, -127, -138, -161, -72, 24, -101,
    67, 30, 1, -91, -71, 3, 36, 96,
    137, 79, 51, 76, 68, 68, 77, 152,
    -38, 196, 197, 151, 101, 199, 200, 30
};
int PSQ_TABLE_PAWN_EG[NSQUARES] = {
    0, 0, 0, 0, 0, 0, 0, 0,
    24, 24, 11, -13, 24, 16, 9, 10,
    22, 26, 12, 15, 14, 22, 7, 8,
    36, 38, 22, 8, 15, 21, 23, 20,
    61, 48, 24, 8, 13, 18, 35, 32,
    82, 75, 54, 13, -10, 17, 33, 52,
    43, 22, 24, -43, -15, 27, 45, 35,
    0, 0, 0, 0, 0, 0, 0, 0
};
int PSQ_TABLE_KNIGHT_EG[NSQUARES] = {
    -21, -42, -18, -1, 1, -25, -38, -106,
    -50, 7, 1, 0, -5, -3, 11, -37,
    -38, 11, 17, 32, 21, -1, -13, -39,
    -4, 30, 45, 27, 38, 30, 10, -11,
    23, 34, 43, 40, 39, 37, 35, 4,
    14, 35, 36, 34, -6, 8, 23, 0,
    -2, 19, 22, 38, 33, 2, -3, -14,
    -39, 43, 22, 22, 14, 43, 37, -73
};
int PSQ_TABLE_BISHOP_EG[NSQUARES] = {
    -1, -13, -5, 9, -2, 8, -23, -26,
    2, -7, -4, 7, 0, 9, -3, -10,
    9, 10, 10, 10, 27, -1, 13, 23,
    23, 5, 11, 9, 6, 26, -4, 7,
    19, 8, 7, 12, 10, 6, 18, -5,
    3, 23, 19, 6, 37, -1, 19, 23,
    13, 1, 37, 42, 19, 29, 19, 0,
    18, 32, 19, 25, 9, 17, 12, 15
};
int PSQ_TABLE_ROOK_EG[NSQUARES] = {
    15, 13, 13, 10, -1, 14, 2, -3,
    8, 19, 19, 5, 5, -3, -22, -4,
    22, 19, 16, 6, -2, 7, -24, -26,
    34, 45, 36, 31, 25, 41, 8, 8,
    42, 47, 43, 38, 27, 42, 26, 24,
    47, 45, 49, 29, 12, 26, 19, 30,
    37, 45, 28, 40, 20, 28, 26, 7,
    29, 37, 35, 36, 42, 48, 46, 33
};
int PSQ_TABLE_QUEEN_EG[NSQUARES] = {
    -67, -68, -67, -20, -60, -37, -53, -19,
    -27, -29, -10, -26, -10, -93, -71, -40,
    -6, -3, 0, -12, 3, 14, 9, -26,
    26, 34, 3, 11, 14, 32, 24, 50,
    -5, 48, 33, 23, 32, 90, 102, 82,
    1, 16, 53, 69, 96, 46, 81, 78,
    8, 70, 64, 108, 101, 58, 87, 58,
    2, 8, 35, 32, 51, 76, 13, 1
};
int PSQ_TABLE_KING_EG[NSQUARES] = {
    -92, -62, -29, -23, -55, -31, -69, -81,
    -19, -12, -2, 10, 3, -2, -16, -33,
    -47, 3, 4, 20, 23, 13, 6, -4,
    -13, 10, 28, 38, 38, 38, 23, 1,
    25, 60, 62, 57, 66, 62, 54, 54,
    29, 56, 64, 66, 64, 74, 90, 36,
    -33, 71, 69, 54, 63, 95, 111, 30,
    -99, -38, 1, 27, 31, 28, 23, -80
};
int KNIGHT_MATERIAL_VALUE_MG = 346;
int BISHOP_MATERIAL_VALUE_MG = 350;
int ROOK_MATERIAL_VALUE_MG = 492;
int QUEEN_MATERIAL_VALUE_MG = 1188;
int KNIGHT_MATERIAL_VALUE_EG = 339;
int BISHOP_MATERIAL_VALUE_EG = 339;
int ROOK_MATERIAL_VALUE_EG = 600;
int QUEEN_MATERIAL_VALUE_EG = 1109;
